cart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('cart/', views.cart_summary, name='cart_summary'),
    path('add_to_cart/<int:variant_id>/<int:source>', views.add_to_cart, name='add_to_cart'),
    path('add_to_cart/<int:variant_id>', views.add_to_cart, name='add_to_cart'),
    path('update_quantity/<int:cart_item_id>/<int:num>', views.update_quantity, name='update_quantity'),
    path('remove_cart_item/<int:cart_item_id>', views.remove_cart_item, name='remove_cart_item'),
    path('wishlist', views.wishlist_summary, name='wishlist_summary'),
    path('add_to_wishlist/<int:variant_id>', views.add_to_wishlist, name='add_to_wishlist'),
    path('remove_from_wishlist/<int:wishlist_item_id>', views.remove_from_wishlist, name='remove_from_wishlist'),
    path('wishlist_to_cart/<int:wishlist_item_id>', views.wishlist_to_cart, name='wishlist_to_cart'),
    path('checkout/', views.checkout, name='checkout'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('', include('users.urls')),
    path('', include('cart.urls')),
    path('', include('promotions.urls')),
    path('', include('orders.urls')),
    path('accounts/', include('allauth.urls')),
    path('adminpanel/', include('adminpanel.urls')),
    path('user_profile/', include('user_profile.urls')),
]

user_profile/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.user_profile, name='user_profile'),
    path('address_management', views.address_management, name='address_management'),
    path('set_as_default/<int:address_id>', views.set_as_default, name='set_as_default'),
    path('delete_address/<int:address_id>', views.delete_address, name='delete_address'),
    path('add_address', views.add_address, name='add_address'),
    path('my_orders', views.my_orders, name='my_orders'),
    path('myorder_detail/<int:order_id>', views.myorder_detail, name='myorder_detail'),
    path('my_wishlist', views.my_wishlist, name='my_wishlist'),
    path('my_wallet', views.my_wallet, name='my_wallet'),
]

user_profile/models.py
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator, RegexValidator
from django.db import models


# Create your models here.
class Address(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    mobile = models.CharField(max_length=10)
    address = models.CharField(max_length=200)
    city = models.CharField(max_length=100)
    district = models.CharField(max_length=100)
    landmark = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    pincode = models.CharField(max_length=10)
    is_default = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.address}, {self.city}, {self.state}, {self.pincode}"

user_profile/views.py
from django.db.models import Sum, Count
from django.shortcuts import render
from cart.models import Wishlist, CartItem, WishlistItem, Wallet
from orders.models import Order
from user_profile.models import Address


# Create your views here.
def user_profile(request):
    address = Address.objects.filter(is_default=True).first()
    cart_count = CartItem.objects.filter(
        cart__user=request.user.id).aggregate(Sum('quantity'))['quantity__sum']
    wishlist_count = WishlistItem.objects.filter(
        wishlist__user=request.user.id).aggregate(Count('variant'))['variant__count']

    context = {
        'cart_count': cart_count,
        'wishlist_count': wishlist_count,
        'address': address,
    }
    return render(request, 'user_profile/user_profile.html', context)


def address_management(request):
    addresses = Address.objects.filter(user__id=request.user.id).order_by('-is_default', 'id')
    cart_count = CartItem.objects.filter(
        cart__user=request.user.id).aggregate(Sum('quantity'))['quantity__sum']
    wishlist_count = WishlistItem.objects.filter(
        wishlist__user=request.user.id).aggregate(Count('variant'))['variant__count']

    context = {
        'cart_count': cart_count,
        'wishlist_count': wishlist_count,
        'addresses': addresses,
    }
    return render(request, 'user_profile/address_management.html', context)


def set_as_default(request, address_id):
    address = Address.objects.get(id=address_id)
    old_default = Address.objects.filter(is_default=True)
    for old in old_default:
        old.is_default = False
        old.save()
    address.is_default = True
    address.save()
    addresses = Address.objects.filter(user__id=request.user.id).order_by('-is_default', 'id')
    return render(request, 'user_profile/address_management.html', {'addresses': addresses})


def delete_address(request, address_id):
    current_address = Address.objects.get(id=address_id)
    if current_address.is_default:
        new_address = Address.objects.exclude(id=address_id).first()
        new_address.is_default = True
        new_address.save()
    current_address.is_active = False
    current_address.save()
    addresses = Address.objects.filter(user__id=request.user.id).order_by('-is_default', 'id')
    return render(request, 'user_profile/address_management.html', {'addresses': addresses})


def add_address(request):
    cart_count = CartItem.objects.filter(
        cart__user=request.user.id).aggregate(Sum('quantity'))['quantity__sum']
    wishlist_count = WishlistItem.objects.filter(
        wishlist__user=request.user.id).aggregate(Count('variant'))['variant__count']

    if request.method == 'POST':
        name = request.POST.get('name')
        mobile = request.POST.get('mobile')
        pincode = request.POST.get('pincode')
        address = request.POST.get('address')
        landmark = request.POST.get('landmark')
        city = request.POST.get('city')
        district = request.POST.get('district')
        state = request.POST.get('state')

        address = Address(
            user=request.user,
            name=name,
            mobile=mobile,
            pincode=pincode,
            address=address,
            landmark=landmark,
            city=city,
            district=district,
            state=state,
        )
        address.save()

        addresses = Address.objects.filter(user__id=request.user.id).order_by('-is_default', 'id')
        context = {
            'cart_count': cart_count,
            'wishlist_count': wishlist_count,
            'addresses': addresses,
        }
        return render(request, 'user_profile/address_management.html', context)

    context = {
        'cart_count': cart_count,
        'wishlist_count': wishlist_count,
    }

    return render(request, 'user_profile/add_address.html', context)


def my_orders(request):
    orders = Order.objects.filter(user=request.user).order_by('-id')
    cart_count = CartItem.objects.filter(
        cart__user=request.user.id).aggregate(Sum('quantity'))['quantity__sum']
    wishlist_count = WishlistItem.objects.filter(
        wishlist__user=request.user.id).aggregate(Count('variant'))['variant__count']

    context = {
        'cart_count': cart_count,
        'wishlist_count': wishlist_count,
        'orders': orders
    }
    return render(request, 'user_profile/myorders.html', context)


def myorder_detail(request, order_id):
    order = Order.objects.get(id=order_id)
    order_items = order.orderitem_set.all()
    context = {
        'order': order,
        'order_items': order_items,
    }
    return render(request, 'user_profile/myorder_detail1.html', context)


def my_wishlist(request):
    wishlist = Wishlist.objects.get(user=request.user.id)
    wishlist_items = wishlist.wishlistitem_set.all()
    cart_count = CartItem.objects.filter(
        cart__user=request.user.id).aggregate(Sum('quantity'))['quantity__sum']
    wishlist_count = WishlistItem.objects.filter(
        wishlist__user=request.user.id).aggregate(Count('variant'))['variant__count']

    context = {
        'cart_count': cart_count,
        'wishlist_count': wishlist_count,
        'wishlist_items': wishlist_items
    }
    return render(request, 'user_profile/profile_wishlist.html', context)


def my_wallet(request):
    wallet = Wallet.objects.get(user=request.user.id)
    balance = wallet.balance
    cart_count = CartItem.objects.filter(
        cart__user=request.user.id).aggregate(Sum('quantity'))['quantity__sum']
    wishlist_count = WishlistItem.objects.filter(
        wishlist__user=request.user.id).aggregate(Count('variant'))['variant__count']

    context = {
        'cart_count': cart_count,
        'wishlist_count': wishlist_count,
        'balance': balance
    }
    return render(request, 'user_profile/wallet.html', context)

user_profile/templates/user_profile/add_address.html
{% extends "user_profile/userprofile_base.html" %}

{% block profile_content %}
            <div class="container-fluid pt-4 px-4">
                <div class="row g-4 d-flex justify-content-center">
                    <div class="col-sm-12 col-xl-9 ">
                        <div class="bg-light rounded h-100 p-4">
                            <h6 class="mb-4">Add Product</h6>
                            <form class="login-form" action="" method="post" enctype="multipart/form-data">
                                {% csrf_token %}

                                <h6 class="mb-4">CONTACT DETAILS</h6>

                                <div class="form-floating mb-3">
                                    <input type="text" class="form-control" id="id_name" name="name"
                                        placeholder="Category Name">
                                    <label for="id_name">Name*</label>
                                </div>

                                <div class="form-floating mb-3">
                                    <input type="number" class="form-control" id="id_mobile" name="mobile"
                                        placeholder="book title">
                                    <label for="id_mobile">Mobile No*</label>
                                </div>

                                <h6 class="mt-4 mb-3">ADDRESS</h6>
                                 <div class="form-floating mb-3">
                                    <input type="number" class="form-control" id="id_pincode" name="pincode"
                                        placeholder="book title">
                                    <label for="id_pincode">Pincode*</label>
                                </div>

                                <div class="form-floating mb-3">
                                    <textarea class="form-control" placeholder="Leave a comment here"
                                        id="id_" name="address" style="height: 150px;"></textarea>
                                    <label for="id_address">Address(Houser No, Building, Street, Area)*</label>
                                </div>


                                <div class="d-flex justify-content-between">
                                    <div class="form-floating mb-3 col-md-6 pe-2">
                                        <input type="text" class="form-control" id="id_landmark" name="landmark"
                                            placeholder="Category Name">
                                        <label for="id_landmark">Landmark*</label>
                                    </div>

                                     <div class="form-floating mb-3 col-md-6 ps-1">
                                        <input type="text" class="form-control" id="id_city" name="city"
                                            placeholder="Category Name">
                                        <label for="id_city">City*</label>
                                    </div>
                                </div>

                                 <div class="d-flex justify-content-between">
                                     <div class="form-floating mb-3 col-md-6 pe-2">
                                        <input type="text" class="form-control" id="id_didtrict" name="district"
                                            placeholder="Category Name">
                                        <label for="id_city">District*</label>
                                    </div>

                                     <div class="form-floating mb-3 col-md-6 ps-1">
                                        <input type="text" class="form-control" id="id_state" name="state"
                                            placeholder="Category Name">
                                        <label for="id_state">State*</label>
                                    </div>
                                </div>



                                <button type="submit" class="btn btn-primary">Add</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <script>
                function previewImage(event) {
                    var input = event.target;
                    var reader = new FileReader();

                    reader.onload = function() {
                        var imgElement = document.getElementById('preview');
                        imgElement.src = reader.result;
                        imgElement.style.display = 'block';
                    };

                    reader.readAsDataURL(input.files[0]);
                }
            </script>


{% endblock profile_content %}

user_profile/templates/user_profile/address_management.html
{% extends "user_profile/userprofile_base.html" %}

{% block profile_content %}
<style>

    .border-box {
        margin-left: 10px;
        width: 265px;
        height: 300px;
        flex-direction: column;
    }
     .addressList-base-addBlock {
      border: 1px dashed #ccc;
      display: flex;
      align-items: center;
      justify-content: center;
      padding: 10px;
      border-radius: 5px;
      cursor: pointer;
    }
</style>

<h2 class="fw-bold m-3">Adresses</h2>

<div class="d-flex flex-wrap p-3">
     <div class="col-lg-4 mb-4">
        <div class="fixed-box" data-action="add">
            <a href="{% url 'add_address' %}" class="border-box  addressList-base-addBlock rounded p-3 d-flex justify-content-center align-items-center">
                <div class="">Add Address</div>
            </a>
        </div>
    </div>

    {% for address in addresses %}
        {% if address.is_active %}
        <div class="col-lg-4 mb-4">
            <div class="fixed-box">
                <div class="border-box border rounded p-3 d-flex justify-content-between">
                    <div>
                        {% if address.is_default %}
                        <div class="border-bottom">
                            <h6>Default</h6>
                        </div>
                        {% endif %}
                        <h6 class="fw-bold mt-3">{{ address.name }}</h6>
                        <h6>{{ address.address }}</h6>
                        <h6>{{ address.landmark }}</h6>
                        <h6>{{ address.city }}, {{ address.pincode }}</h6>
                        <h6>{{ address.district }}, {{ address.state }}</h6>
                        <h6>Phone number: {{ address.mobile }}</h6>

                    </div>
                    <div class="d-flex justify-content-start">
                        <a href="#"><h6>Edit</h6></a>
                        <h6 class="fw-bold mx-1">|</h6>
                        <div><a href="{% url 'delete_address' address.id %}"><h6>Remove</h6></a></div>
                        {% if not address.is_default %}
                        <h6 class="fw-bold mx-1">|</h6>
                        <div><a href="{% url 'set_as_default' address.id %}"><h6>Set as Default</h6></a></div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        {% endif %}
    {% endfor %}
</div>



{% endblock profile_content %}

user_profile/templates/user_profile/myorder_detail.html
{% extends "user_profile/userprofile_base.html" %}

{% block profile_content %}

<style>
    /* Custom styles for the template */
    .address-box {
        border: 1px solid #dee2e6;
        border-radius: 5px;
        padding: 15px;
        background-color: #f8f9fa;
    }
    .inline-boxes {
        display: flex;
        justify-content: space-between;
    }
</style>

<div class="container px-5">

      <div class="dropdown d-flex justify-content-between my-4">
        <h2>Order Products</h2>
          {% if order.order_status != 'CANCELLED' and order.order_status != 'RETURNED' %}

        <a href="{% url 'change_order_status' order.id 'Cancelled' %}" class="btn btn-danger dropdown-toggle" type="button" id="changeStatusDropdown" data-bs-toggle="dropdown" aria-expanded="false">Cancel Order</a>


        {% endif %}
    </div>




    <table class="table table-striped table-bordered mt-3">
        <thead class="thead-light">
            <tr>
                <th scope="col">Product</th>
                <th scope="col">Image</th>
                <th scope="col">Price</th>
                <th scope="col">Quantity</th>
                <th scope="col">Total price</th>
            </tr>
        </thead>
        <tbody>
            {% for item in order_items %}
            <tr>
                <td>{{ item.variant }}</td>
                <td>
                    <img src="{{ item.variant.image.url }}" alt="{{ order_item.product.name }}"
                        class="img-thumbnail" style="height:70px;width:50px;">
                </td>
                <td>{{ item.variant.price }}</td>
                <td>{{ item.quantity }}</td>
                <td>{{ item.price }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <!-- Div to display address and order details inline -->
    <div class="inline-boxes mt-4">
        <!-- Order details box -->
       <div class="order-details">
            <h2>Order Details</h2>
            <p><strong>Order ID:</strong> {{ order.id }}</p>
            <p><strong>Order Date:</strong>  {{ order.order_date }}</p>
            {% if order_view.payment_status != 'CANCELLED' and order_view.payment_status != 'RETURNED' %}
                <p><strong>Delivery Date:</strong> {{ order_view.delivery_date }}</p>
            {% endif %}
            <p><strong>Payment Method:</strong> {{ order.payment_method }}</p>
            <p><strong>Order status:</strong><span class="font-weight-bold text-danger mx-2">{{ order.payment_status }}</span></p>

            <!-- Submit button for processing the order -->
            {% if order_view.payment_status == 'PENDING' %}
                <form action="{% url 'process_order' order_view.id %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-primary">Process Order</button>
                </form>
            {% endif %}
        </div>

        <!-- Address box -->
        <div class="address-box ml-4">
            <h2>Order Address</h2>
            <p><strong>Name:</strong> {{ order.address.name }}</p>
            <p><strong>Address:</strong> {{ order.address.address }}</p>
            {% if order_view.address.address_line2 %}
            <p><strong>Address Line 2:</strong> {{ order_view.address.address_line2 }}</p>
            {% endif %}
            <p><strong>City:</strong> {{ order.address.city }}</p>
            <p><strong>Zip Code:</strong> {{ order.address.pincode }}</p>
            <p><strong>State:</strong> {{ order.address.state }}</p>
            <p><strong>Phone Number:</strong> {{ order.address.mobile }}</p>
        </div>
    </div>

</div>

{% endblock profile_content %}

user_profile/templates/user_profile/myorders.html
{% extends "user_profile/userprofile_base.html" %}

{% block profile_content %}

            <div class="col-lg-12">
              <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col">
                  {% for order in orders %}
                  <div class="card card-stepper m-3 mb-4" style="border-radius: 10px; margin-bottom: 40px; border-radius: 1rem; max-width: 100%; box-shadow: 0 6px 12px rgba(0, 0, 0, 0.2);">
                    <div class="card-body p-4" style="padding-bottom: 20px;">
                      <div class="d-flex justify-content-between align-items-center">
                        <div class="d-flex flex-column">
                          <span class="lead fw-normal">Order Id: LTHB00202314{{ order.id }}</span>
                          <span class="text-muted small">Name : {{ order.address.name }} {{orders.user.last_name}}</span>
                          <span class="text-muted small">Delivery Address : {{ order.address.address }}</span>
                          <span class="text-muted ">Items :{{ order.price }}</span>
                        </div>
                        <div>
                          <a href="{% url 'myorder_detail' order.id %}" class="btn btn-outline-success" role="button">Order Details</a>
                        </div>
                      </div>
                      <hr class="my-4">
                      <div class="d-flex flex-row justify-content-between align-items-center">
                        <div class="d-flex flex-column align-items-start"><span>Ordered Date</span><span class="text-muted small">{{ order.order_date.date }}</span></div>
                        <div class="d-flex flex-column justify-content-center"><span >Payment Method</span><span class="text-muted small">{{ order.payment_method }}</span></div>
                        <div class="d-flex flex-column justify-content-center align-items-center"><span>Current Status</span><span class="text-muted small">{{ order.order_status }}</span></div>
                        <div class="d-flex flex-column align-items-center"><span>Payment Status</span><span class="text-muted small">{{ order.payment_status }}</span></div>
                      </div>
                    </div>
                  </div>
                  {% endfor %}
                </div>
          </div>
        </div>

{% endblock profile_content %}

user_profile/templates/user_profile/profile_wishlist.html
{% extends "user_profile/userprofile_base.html" %}

{% load static %}


{% block profile_content %}
 <!-- Cart Start -->
  <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">

    <link href="{% static 'store/css/stylee.css' %}" rel="stylesheet">

    <style>
    .card-header{
        height: 250px; /* Adjust the height as needed */
    }

    </style>


            <div class="wishlist-heading ms-5 mt-4 pt-3">
                <h4 class="">My Wishlist <span style="font-weight: 300;">{{ wishlist_count }} items</span></h4>
            </div>

            <div class="mt-3 pt-3 px-5">
                <div class="row">
                {% for item in wishlist_items %}
                <div class="col-lg-3 col-md-3 col-sm-4 col-6 mb-4">
                    <div class="card product-item border-0 mb-4">
                        <a href="{% url 'product_details' item.variant.slug %}" class="card-header product-img position-relative overflow-hidden bg-transparent border p-0">
                            <img class="img-fluid w-100" src="{{ item.variant.image.url }}" alt="">
                        </a>
                        <div class="card-body border text-center p-0 pt-3 pb-2">
                            <h6 class="text-truncate mb-3"> {{ item.variant.book.name }} - {{ item.variant.language }} - {{ item.variant.cover_type }}</h6>
                            <div class="d-flex justify-content-center">
                                <h6>₹{{ item.variant.price }}</h6><h6 class="text-muted ml-2"><del>₹{{ item.variant.price }}</del></h6>
                            </div>
                        </div>
                            <a href="{% url 'wishlist_to_cart' item.id %}" class="card-footer d-flex justify-content-center bg-light border text-decoration-none">
                                <div class="btn btn-sm text-dark p-0"><i class="fas fa-shopping-cart text-success mr-1"></i>Move To Cart</div>
                            </a>
                        </div>
                    </div>

                {% endfor %}
                </div>
            </div>

    <!-- Cart End -->


{% endblock profile_content %}

user_profile/templates/user_profile/user_profile.html
{% extends "user_profile/userprofile_base.html" %}

{% block profile_content %}

              <ul class="nav nav-tabs nav-tabs-bordered">

                <li class="nav-item">
                  <button class="nav-link active" data-bs-toggle="tab" data-bs-target="#profile-overview">Overview</button>
                </li>

                <li class="nav-item">
                  <button class="nav-link" data-bs-toggle="tab" data-bs-target="#profile-edit">Edit Profile</button>
                </li>

                <li class="nav-item">
                  <button class="nav-link" data-bs-toggle="tab" data-bs-target="#profile-settings">Settings</button>
                </li>

                <li class="nav-item">
                  <button class="nav-link" data-bs-toggle="tab" data-bs-target="#profile-change-password">Change Password</button>
                </li>
              </ul>
              <div class="tab-content pt-2">

                <div class="tab-pane fade show active profile-overview" id="profile-overview">
<!--                  <h5 class="card-title">About</h5>-->
<!--                  <p class="small fst-italic">Sunt est soluta temporibus accusantium neque nam maiores cumque temporibus. Tempora libero non est unde veniam est qui dolor. Ut sunt iure rerum quae quisquam autem eveniet perspiciatis odit. Fuga sequi sed ea saepe at unde.</p>-->

                  <h5 class="my-4">Profile Details</h5>

                  <div class="row">
                    <div class="col-lg-3 col-md-4 label ">Userame</div>
                    <div class="col-lg-9 col-md-8">{{ user.username }}</div>
                  </div>

<!--                  <div class="row">-->
<!--                    <div class="col-lg-3 col-md-4 label">Company</div>-->
<!--                    <div class="col-lg-9 col-md-8">Lueilwitz, Wisoky and Leuschke</div>-->
<!--                  </div>-->

<!--                  <div class="row">-->
<!--                    <div class="col-lg-3 col-md-4 label">Job</div>-->
<!--                    <div class="col-lg-9 col-md-8">Web Designer</div>-->
<!--                  </div>-->

<!--                  <div class="row">-->
<!--                    <div class="col-lg-3 col-md-4 label">Country</div>-->
<!--                    <div class="col-lg-9 col-md-8">USA</div>-->
<!--                  </div>-->

                  <div class="row">
                    <div class="col-lg-3 col-md-4 label">Address</div>
                    <div class="col-lg-9 col-md-8">{{ address.address }}, {{ address.city }}, {{ address.district }}, {{ address.state }}</div>
                  </div>

                  <div class="row">
                    <div class="col-lg-3 col-md-4 label">Phone</div>
                    <div class="col-lg-9 col-md-8">{{ address.mobile }}</div>
                  </div>

                  <div class="row">
                    <div class="col-lg-3 col-md-4 label">Email</div>
                    <div class="col-lg-9 col-md-8">{{ user.email }}</div>
                  </div>

                </div>


{% endblock profile_content %}

user_profile/templates/user_profile/userprofile_base.html
{% extends "store/base.html" %}
{% load static %}

{% block style %}

    <link href="{% static 'store/css/user_profilee.css' %}" rel="stylesheet">

<!--    <link href="{% static 'adminpanel/css/style.css' %}" rel="stylesheet">-->

{% endblock %}
{% block new_style %}{% endblock %}


{% block content %}

<div class="main">
  <div class="m-5">
    <section class="section profile">
      <div class="row">
        <div class="col-xl-3">

          <div class="card">
            <div class="card-body profile-card pt-4 d-flex flex-column align-items-center">

              <img src="{% static 'store/img/bookbanner.jfif' %}" alt="Profile" class="rounded-circle">
              <h2>{{ user.username }}</h2>
              <h3>{{ user.email }}</h3>
              <div class="social-links mt-2">
                <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
                <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
                <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
                <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></a>
              </div>
            </div>
          </div>

          <div class="card sticky-top">
            <div class="card-body profile-card pt-4 d-flex flex-column align-items-center">
              <div class="navbar-nav w-100">
                    <a href="{% url 'user_profile' %}" class="nav-item nav-link"><i class="fa fa-user me-2"></i>Profile Information</a>
                    <a href="{% url 'address_management' %}" class="nav-item nav-link"><i class="fa fa-home me-2"></i>Address Management</a>
                    <a href="{% url 'my_orders' %}" class="nav-item nav-link"><i class="fa fa-box me-2"></i>My Orders</a>
                    <a href="{% url 'my_wishlist' %}" class="nav-item nav-link"><i class="fa fa-heart me-2"></i>My Wishlist</a>
                    <a href="{% url 'my_wallet' %}" class="nav-item nav-link"><i class="fa fa-wallet me-2"></i>My Wallet</a>
              </div>

            </div>
          </div>
        </div>

        <div class="col-xl-9">
          <div class="card">
            <div class="card-body pt-3">
              <!-- Bordered Tabs -->
                {% block profile_content %}{% endblock %}
              <!-- End Bordered Tabs -->

            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
</div>



{% endblock content %}

user_profile/templates/user_profile/wallet.html
{% extends "user_profile/userprofile_base.html" %}

{% block profile_content %}


    <h1>My Wallet</h1>
    <p>Your current balance: ₹{{ balance }}</p>

{% endblock profile_content %}