adminpanel/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.admin_home, name='admin-home'),
    path('category_list/', views.category_list, name='admin-category_list'),
    path('create_category/', views.create_category, name='admin-create_category'),
    path('users_list/', views.users_list, name='admin-users_list'),
    path('products_list/', views.products_list, name='admin-products_list'),
    path('enable_category/<int:category_id>', views.enable_category, name='enable_category'),
    path('disable_category/<int:category_id>', views.disable_category, name='disable_category'),
    path('delete_category/<int:category_id>', views.delete_category, name='delete_category'),
    path('edit_category/<int:category_id>', views.edit_category, name='edit_category'),
    path('block_user/<int:user_id>', views.block_user, name='block_user'),
    path('unblock_user/<int:user_id>', views.unblock_user, name='unblock_user'),
    path('delete_user/<int:user_id>', views.delete_user, name='delete_user'),
    path('edit_product/<int:book_id>', views.edit_product, name='edit_product'),
    path('add_product', views.add_product, name='add_product'),
    path('enable_product/<int:book_id>', views.enable_product, name='enable_product'),
    path('process_image/', views.process_image, name='process_image'),
    path('disable_product/<int:book_id>', views.disable_product, name='disable_product'),
    path('view_product_variants/<int:book_id>', views.view_product_variants, name='view_product_variants'),
    path('edit_variant/<int:variant_id>/<int:book_id>', views.edit_variant, name='edit_variant'),
    path('enable_variant/<int:variant_id>/<int:book_id>', views.enable_variant, name='enable_variant'),
    path('disable_variant/<int:variant_id>/<int:book_id>', views.disable_variant, name='disable_variant'),
    path('add_variant/<int:book_id>', views.add_variant, name='add_variant'),
    path('orders_list/', views.orders_list, name='orders_list'),
    path('change_order_status/<int:order_id>/<str:status>', views.change_order_status, name='change_order_status'),
    path('admin_order_details/<int:order_id>', views.admin_order_details, name='admin_order_details'),
    path('coupon_management/', views.coupon_management, name='coupon_management'),
    path('add_coupon/', views.add_coupon, name='add_coupon'),
    path('edit_coupon/<int:coupon_id>', views.edit_coupon, name='edit_coupon'),
    path('activate_coupon/<int:coupon_id>/<str:action>', views.activate_coupon, name='activate_coupon'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('sales_report', views.sales_report, name='sales_report'),
    path('initiate_refund/<int:order_id>', views.initiate_refund, name='initiate_refund'),
]

cart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('cart/', views.cart_summary, name='cart_summary'),
    path('add_to_cart/<int:variant_id>/<int:source>', views.add_to_cart, name='add_to_cart'),
    path('add_to_cart/<int:variant_id>', views.add_to_cart, name='add_to_cart'),
    path('update_quantity/<int:cart_item_id>/<int:num>', views.update_quantity, name='update_quantity'),
    path('remove_cart_item/<int:cart_item_id>', views.remove_cart_item, name='remove_cart_item'),
    path('wishlist', views.wishlist_summary, name='wishlist_summary'),
    path('add_to_wishlist/<int:variant_id>', views.add_to_wishlist, name='add_to_wishlist'),
    path('remove_from_wishlist/<int:wishlist_item_id>', views.remove_from_wishlist, name='remove_from_wishlist'),
    path('wishlist_to_cart/<int:wishlist_item_id>', views.wishlist_to_cart, name='wishlist_to_cart'),
    path('checkout/', views.checkout, name='checkout'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('', include('users.urls')),
    path('', include('cart.urls')),
    path('', include('promotions.urls')),
    path('', include('orders.urls')),
    path('accounts/', include('allauth.urls')),
    path('adminpanel/', include('adminpanel.urls')),
    path('user_profile/', include('user_profile.urls')),
]

adminpanel/models.py
from django.db import models

# Create your models here.

promotions/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone


# Create your models here.
class Coupon(models.Model):
    code = models.CharField(max_length=20, unique=True)
    discount_type = models.CharField(max_length=10, choices=[('percentage', 'Percentage'), ('fixed', 'Fixed')],
                                     default='percentage')
    discount_value = models.DecimalField(max_digits=5, decimal_places=0)
    min_or_max_amount = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    activation_date = models.DateTimeField(default=timezone.now)
    expiration_date = models.DateTimeField(default=timezone.now)
    is_onetime_usable = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.code


class UsedCoupon(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    coupon = models.ForeignKey(Coupon, on_delete=models.CASCADE)
    used_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('user', 'coupon')

    def __str__(self):
        return f"{self.user.username} used {self.coupon.code} on {self.used_date}"

store/models.py
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.text import slugify
from image_cropping.fields import ImageCropField


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, unique=True)
    image = models.ImageField(upload_to='category_images/')
    offer_percentage = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    is_active = models.BooleanField(default=True)
    description = models.TextField(null=True)

    class Meta:
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        # Generate slug from the name field
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)


class Author(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True)
    description = models.TextField()
    image = models.ImageField(default='default_author.jpg', upload_to='author_images/')

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)


class Publisher(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class CoverType(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=255, unique=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)


class Language(models.Model):
    name = models.CharField(default='English', max_length=50)
    slug = models.SlugField(max_length=255, unique=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)


class Book(models.Model):
    name = models.CharField(max_length=255)
    title = models.CharField(max_length=255)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    no_of_pages = models.PositiveSmallIntegerField()
    publisher = models.ForeignKey(Publisher, on_delete=models.CASCADE)
    offer_percentage = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    description = models.TextField()
    cover_image = ImageCropField(upload_to='book_covers/')
    is_active = models.BooleanField(default='True')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    slug = models.SlugField(max_length=255, unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name


class BookVariant(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    cover_type = models.ForeignKey(CoverType, on_delete=models.CASCADE)
    language = models.ForeignKey(Language, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    offer_price = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    offer_percentage = models.PositiveIntegerField(default=0)
    image = models.ImageField(upload_to='variant_cover_image/')
    is_active = models.BooleanField(default='True')
    stock = models.PositiveIntegerField()
    slug = models.SlugField(max_length=255)

    def calculate_offer_price(self):
        category_offer = self.book.category.offer_percentage if self.book.category.offer_percentage else 0
        product_offer = self.book.offer_percentage if self.book.offer_percentage else 0
        variant_offer = max(category_offer, product_offer)
        self.offer_price = self.price * (1 - variant_offer / 100) if variant_offer != 0 else None
        self.offer_percentage = variant_offer if variant_offer != 0 else 0

    def save(self, *args, **kwargs):
        self.calculate_offer_price()
        self.slug = slugify(f"{self.book.name}-{self.cover_type.name}-{self.language.name}")
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.book.name}-{self.cover_type.name}-{self.language.name}"


@receiver(post_save, sender=Category)
@receiver(post_save, sender=Book)
def update_offer_prices_for_variants(sender, instance, **kwargs):
    variants = BookVariant.objects.filter(book__category=instance) if isinstance(instance, Category) else BookVariant.objects.filter(book=instance)
    for variant in variants:
        variant.calculate_offer_price()
        variant.save()


class VariantImages(models.Model):
    image = models.ImageField(upload_to='variant_images/')
    book_variant = models.ForeignKey(BookVariant, on_delete=models.CASCADE)

    def __str__(self):
        return f"Variant: {self.book_variant} - Image: {self.image.name}"

adminpanel/templates/adminpanel/add_coupon.html
{% extends "adminpanel/admin_base.html" %}

{% block content %}
            <div class="container-fluid pt-4 px-4">
                <div class="row g-4 d-flex justify-content-center">
                    <div class="col-sm-12 col-xl-6 ">
                        <div class="bg-light rounded h-100 p-4">
                            <h6 class="mb-4">Add Coupon</h6>
                            <form class="login-form" action="" method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="form-floating mb-3">
                                    <input type="text" class="form-control" id="id_code" name="code"
                                        placeholder="Code">
                                    <label for="id_code">Code</label>
                                </div>


                                <div class="form-floating mb-3">
                                    <select class="form-select" id="discount_typeSelect" name="discount_typeSelect"
                                        aria-label="Floating label select example">
                                        <option value="pecentage" selected>Percentage</option>
                                        <option value="fixed">Fixed</option>
                                    </select>
                                    <label for="discount_typeSelect">Discount Type</label>
                                </div>

                                <div class="form-floating mb-3">
                                    <input type="number" class="form-control" id="id_discount_value" name="discount_value"
                                        placeholder="No of pages">
                                    <label for="id_discount_value">Discount Value</label>
                                </div>

                                <div class="form-floating mb-3">
                                    <input type="number" class="form-control" id="id_min_or_max_amount" name="min_or_max_amount"
                                        placeholder="No of pages">
                                    <label for="id_min_or_max_amount">Maximum Dicount or Minimum Purchase Amount</label>
                                </div>


                               <div class="form-floating mb-3">
                                    <input type="datetime-local" class="form-control" id="id_activation_date" name="activation_date">
                                    <label for="id_activation_date">Activation Date</label>
                                </div>

                                <div class="form-floating mb-3">
                                    <input type="datetime-local" class="form-control" id="id_expiration_date" name="expiration_date">
                                    <label for="id_expiration_date">Expiration Date</label>
                                </div>

                                <div class="form-check form-check-inline">
                                    <input class="form-check-input" type="checkbox" value="True" id="id_onetimeusable" name="onetimeusable" checked>
                                    <label class="form-check-label" for="id_onetimeusable">One Time Usable</label>
                                </div>

                                <br>
                                <button type="submit" class="btn btn-primary mt-3">Add</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

          <script>
            // Get the current date
            const currentDate = new Date();
            // Set the time to midnight (00:00)
            currentDate.setHours(0, 0, 0, 0);

            // Calculate the next 30 days
            const next30Days = new Date(currentDate);
            next30Days.setDate(next30Days.getDate() + 30);

            // Format the dates in the required format for datetime-local input (YYYY-MM-DDTHH:mm)
            const formattedCurrentDate = currentDate.toISOString().slice(0, 16);
            const formattedNext30Days = next30Days.toISOString().slice(0, 16);

            // Set the default values for the input elements
            document.getElementById("id_activation_date").value = formattedCurrentDate;
            document.getElementById("id_expiration_date").value = formattedNext30Days;
        </script>


{% endblock content %}

adminpanel/templates/adminpanel/admin_add_category.html
{% extends "adminpanel/admin_base.html" %}

{% block content %}
            <div class="container-fluid pt-4 px-4">
                <div class="row g-4 d-flex justify-content-center">
                    <div class="col-sm-12 col-xl-6 ">
                        <div class="bg-light rounded h-100 p-4">
                            <h6 class="mb-4">Add category</h6>
                            <form class="login-form" action="" method="post" enctype="multipart/form-data">
                                {% csrf_token %}

                                <div class="form-floating mb-3">
                                    <input type="text" class="form-control" id="id_name" name="name"
                                        placeholder="Category Name">
                                    <label for="id_name">Name</label>
                                </div>

                                <div class="form-floating mb-3">
                                    <textarea class="form-control" placeholder="Leave a comment here"
                                        id="id_description" name="description" style="height: 150px;"></textarea>
                                    <label for="id_description">Description (optional)</label>
                                </div>

                                <div class="mb-3">
                                    <label for="id_image" class="form-label">Image</label>
                                    <input type="file" class="form-control" id="id_image" name="image" onchange="previewImage(event)">
                                    <img id="preview" src="#" alt="Category Image Preview" width="100" height="100" style="display: none;">
                                </div>

                                <button type="submit" class="btn btn-primary">Add</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <script>
                function previewImage(event) {
                    var input = event.target;
                    var reader = new FileReader();

                    reader.onload = function() {
                        var imgElement = document.getElementById('preview');
                        imgElement.src = reader.result;
                        imgElement.style.display = 'block';
                    };

                    reader.readAsDataURL(input.files[0]);
                }
            </script>


{% endblock content %}

adminpanel/templates/adminpanel/admin_category_list.html
{% extends "adminpanel/admin_base.html" %}

{% block content %}

                    <div class="col-sm-12">
                        <div class="bg-white rounded h-100 p-4">
                            <div class="d-flex justify-content-between mx-3">
                                <div><h6 class="mb-4">Catgory list</h6></div>
                                <div class="ml-5 pl-5"><a  href="{% url 'admin-create_category' %}" class="btn btn-sm btn-primary rounded-pill">+ Add Category</a></div>
                            </div>
                            <table class="table table-hover mt-2">
                                <thead>
                                    <tr>
                                        <th scope="col">No</th>
                                        <th scope="col">Image</th>
                                        <th scope="col">Id</th>
                                        <th scope="col">Name</th>
                                        <th scope="col">Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                {% for category in categoies %}
                                    <tr>
                                        <th scope="row">{{ forloop.counter }}</th>
                                         <td>
                                            <img src="{{ category.image.url }}" alt="{{ category.name }} Image" width="40" height="40">
                                        </td>
                                        <td>{{ category.id }}</td>
                                        <td>{{ category.name }}</td>

                                        <td>
                                            <a  href="{% url 'edit_category' category.id %}" class="btn btn-outline-info m-1">Edit</a>
                                            {% if category.is_active %}
                                                <a  href="{% url 'disable_category' category.id %}" class="btn btn-outline-danger m-1">Disable</a>
                                            {% else %}
                                                 <a  href="{% url 'enable_category' category.id %}" class="btn btn-outline-success m-1">Enable</a>
                                            {% endif %}
<!--                                            <a  href="{% url 'delete_category' category.id %}" class="btn btn-outline-light m-2">Del</a>-->


                                        </td>


                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="pagination  d-flex justify-content-end me-5 pe-5">
                            {% if categoies.has_previous %}
                                <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
                                <a class="btn btn-outline-info mb-4" href="?page={{ categoies.previous_page_number }}">Prev</a>
                            {% endif %}

                            {% for num in categoies.paginator.page_range %}
                                {% if users.number == num %}
                                    <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
                                {% elif num > categoies.number|add:'-3' and num < categoies.number|add:'3' %}
                                     <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
                                {% endif %}
                            {% endfor %}

                             {% if categoies.has_next %}
                                <a class="btn btn-outline-info mb-4" href="?page={{ categoies.next_page_number }}">Next</a>
                                <a class="btn btn-outline-info mb-4" href="?page={{ categoies.paginator.num_pages}}">Last</a>
                            {% endif %}
                    </div>

{% endblock content %}

adminpanel/templates/adminpanel/edit_category.html
{% extends "adminpanel/admin_base.html" %}

{% block content %}
            <div class="container-fluid pt-4 px-4">
                <div class="row g-4 d-flex justify-content-center">
                    <div class="col-sm-12 col-xl-6 ">
                        <div class="bg-light rounded h-100 p-4">
                            <h6 class="mb-4">Edit category</h6>
                            <form class="login-form" action="" method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="form-floating mb-3">
                                    <input type="text" class="form-control"  value="{{ category.name }}" id="id_name" name="name"
                                        placeholder="Category Name">
                                    <label for="id_name">Name</label>
                                </div>

                                <div class="form-floating mb-3">
                                    <textarea class="form-control" placeholder="Leave a comment here"
                                        id="id_description" name="description" style="height: 150px;"></textarea>
                                    <label for="id_description">Description (optional)</label>
                                </div>

                                <div class="form-floating mb-3">
                                    <input type="number" class="form-control" id="id_offer_percentage" name="offer_percentage" value="{{ category.offer_percentage }}"
                                        placeholder="No of pages">
                                    <label for="id_offer_percentage">Offer Percentage</label>
                                </div>

                                <div class="mb-3">
                                    <label for="id_image" class="form-label">Image</label>
                                    <input type="file" class="form-control" id="id_image" name="image" onchange="previewImage(event)">
                                    <img id="preview" src="#" alt="Category Image Preview" width="100" height="100" style="display: none;">
                                </div>

                                <button type="submit" class="btn btn-primary">Edit</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <script>
                function previewImage(event) {
                    var input = event.target;
                    var reader = new FileReader();

                    reader.onload = function() {
                        var imgElement = document.getElementById('preview');
                        imgElement.src = reader.result;
                        imgElement.style.display = 'block';
                    };

                    reader.readAsDataURL(input.files[0]);
                }
            </script>


{% endblock content %}

adminpanel/templates/adminpanel/edit_product.html
{% extends "adminpanel/admin_base.html" %}

{% block content %}
            <div class="container-fluid pt-4 px-4">
                <div class="row g-4 d-flex justify-content-center">
                    <div class="col-sm-12 col-xl-6 ">
                        <div class="bg-light rounded h-100 p-4">
                            <h6 class="mb-4">Add Product</h6>
                            <form class="login-form" action="" method="post" enctype="multipart/form-data">
                                {% csrf_token %}


                                <div class="form-floating mb-3">
                                    <input type="text" class="form-control" id="id_name" name="name" value="{{ book.name }}"
                                        placeholder="Category Name">
                                    <label for="id_name">Name</label>
                                </div>

                                <div class="form-floating mb-3">
                                    <input type="text" class="form-control" id="id_title" name="title" value="{{ book.title }}"
                                        placeholder="book title">
                                    <label for="id_title">Title</label>
                                </div>

                                <div class="form-floating mb-3  col-sm-11">
                                    <select class="form-select" id="categorySelect" name="categorySelect" value="{{ book.category }}"
                                        aria-label="Floating label select example">
                                        <option selected value="{{ book.category.id }}">{{ book.category }}</option>
                                        {% for category in categories %}
                                            <option value="{{ category.id }}">{{ category.name }}</option>
                                        {% endfor %}
                                    </select>
                                    <label for="categorySelect">Category</label>
                                </div>

                                 <div class="form-floating mb-3">
                                    <select class="form-select" id="authorSelect" name="authorSelect"
                                        aria-label="Floating label select example">
                                        <option selected value="{{ book.author.id }}">{{ book.author }}</option>
                                        {% for author in authors %}
                                        <option value="{{ author.id }}">{{ author.name }}</option>
                                        {% endfor %}
                                    </select>
                                    <label for="authorSelect">Author</label>
                                </div>

                                 <div class="form-floating mb-3">
                                    <select class="form-select" id="publisherSelect" name="publisherSelect" value="{{ book.publisher }}"
                                        aria-label="Floating label select example">
                                        <option selected value="{{ book.publisher.id }}">{{ book.publisher }}</option>
                                        {% for publisher in publishers %}
                                        <option value="{{ publisher.id }}">{{ publisher.name }}</option>
                                        {% endfor %}
                                    </select>
                                    <label for="publisherSelect">Publisher</label>
                                </div>

                                <div class="form-floating mb-3">
                                    <input type="number" class="form-control" id="id_pagenum" name="pagenum" value="{{ book.no_of_pages }}"
                                        placeholder="No of pages">
                                    <label for="id_name">No of Pages</label>
                                </div>

                                <div class="form-floating mb-3">
                                    <input type="number" class="form-control" id="id_offer_percentage" name="offer_percentage" value="{{ book.offer_percentage }}"
                                        placeholder="No of pages">
                                    <label for="id_offer_percentage">Offer Percentage</label>
                                </div>

                                <div class="form-floating mb-3">
                                    <textarea class="form-control" placeholder="Leave a comment here" value="{{ book.description }}"
                                        id="id_description" name="description" style="height: 150px;"></textarea>
                                    <label for="id_description">Description (optional)</label>
                                </div>

                                <div class="mb-3">
                                    <label for="id_image" class="form-label">Cover Image</label>
                                    <input type="file" class="form-control" id="id_image" name="image" value="{{ book.cover_image }}" onchange="previewImage(event)">
                                    <img id="preview" src="#" alt="Category Image Preview" width="100" height="100" style="display: none;">
                                </div>

                                <button type="submit" class="btn btn-primary">Add</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <script>
                function previewImage(event) {
                    var input = event.target;
                    var reader = new FileReader();

                    reader.onload = function() {
                        var imgElement = document.getElementById('preview');
                        imgElement.src = reader.result;
                        imgElement.style.display = 'block';
                    };

                    reader.readAsDataURL(input.files[0]);
                }
            </script>


{% endblock content %}